version: '2.1'
 
services:

  db:
    build: ./db
    env_file:
      - environment.properties
    volumes:
      - ./db/data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 15
      
  backend:
    restart: always
    build: ./backend
    env_file:
      - environment.properties
    command: /usr/local/bin/gunicorn -c gunicorn.cfg api:app
    depends_on:
      db:
        condition: service_healthy
    
  server:
    restart: always
    build: ./server
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/var/www/html
