version: '2.1'
 
services:

  db:
    build: ./db
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - $DB_PATH:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --username=$DB_USER --dbname=$DB_NAME
      interval: 5s
      
  backend:
    restart: always
    build: ./backend
    env_file:
      - .env
    command: /usr/local/bin/gunicorn -c gunicorn.cfg api:app
    depends_on:
      db:
        condition: service_healthy
    
  server:
    restart: always
    build: ./server
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/var/www/html
